
# 混合端口 HTTP和SOCKS5用一个端口
mixed-port: 7893
# TCP 并发连接所有 IP, 将使用最快握手的 TCP
tcp-concurrent: true
# 允许局域网的连接（可用来共享代理）
allow-lan: true
# 开启 IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录  
ipv6: false
# 规则模式：rule/global/direct/script
mode: rule
# 设置日志输出级别: silent/error/warning/info/debug
log-level: info
# 全局 TLS 指纹
global-client-fingerprint: chrome
# 匹配所有进程（always/strict/off）
find-process-mode: strict

# 使用geoip.dat数据库
geodata-mode: true
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
                         
profile:
  # 存储 select 选择记录
  store-selected: true 
  # 持久化 fake-ip
  store-fake-ip: true

# Tun 配置  
tun:
  enable: false
  # 可选： system/gvisor/mixed；
  stack: mixed
  # dns劫持,一般设置为 any:53 即可, 即劫持所有53端口的udp流量
  dns-hijack: [any:53]
  # 自动设置全局路由，可以自动将全局流量路由进入tun网卡。
  auto-route: true
  # 自动识别出口网卡
  auto-detect-interface: true
        
dns:
    enable: true # 关闭将使用系统 DNS
    prefer-h3: true # 开启 DoH 支持 HTTP/3，将并发尝试
    listen: ':53' # 开启 DNS 服务器监听
    default-nameserver:
        - 114.114.114.114
        - 8.8.8.8
        - tls://223.5.5.5:853
        - 192.168.31.1 # 如果是windows或安卓客户端可使用system，如果是软路由填写你的拨号光猫/路由器的IP地址

    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter:   #这里可以填写不使用fakeip的域名
        - '*.lan'
        - '*.battlenet.com.cn'
        - '*.battlenet.com'
        - '*.blzstatic.cn'
        - '*.battle.net'
        # === Linksys Wireless Router ===
        - '*.linksys.com'
        - '*.linksyssmartwifi.com'
        # === Apple Software Update Service ===
        - 'swscan.apple.com'
        - 'mesu.apple.com'
        # === Windows 10 Connnect Detection ===
        - '*.msftconnecttest.com'
        - '*.msftncsi.com'
        # === NTP Service ===
        - 'time.*.com'
        - 'time.*.gov'
        - 'time.*.edu.cn'
        - 'time.*.apple.com'
        - 'time1.*.com'
        - 'time2.*.com'
        - 'time3.*.com'
        - 'time4.*.com'
        - 'time5.*.com'
        - 'time6.*.com'
        - 'time7.*.com'
        - 'ntp.*.com'
        - 'ntp.*.com'
        - 'ntp1.*.com'
        - 'ntp2.*.com'
        - 'ntp3.*.com'
        - 'ntp4.*.com'
        - 'ntp5.*.com'
        - 'ntp6.*.com'
        - 'ntp7.*.com'
        - '*.time.edu.cn'
        - '*.ntp.org.cn'
        - '+.pool.ntp.org'
        - 'time1.cloud.tencent.com'
        # === Music Service ===
        ## NetEase
        - '+.music.163.com'
        - '*.126.net'
        ## Baidu
        - 'musicapi.taihe.com'
        - 'music.taihe.com'
        ## Kugou
        - 'songsearch.kugou.com'
        - 'trackercdn.kugou.com'
        ## Kuwo
        - '*.kuwo.cn'
        ## JOOX
        - 'api-jooxtt.sanook.com'
        - 'api.joox.com'
        - 'joox.com'
        ## QQ
        - '*.qq.com'
        - 'report.url.cn'
        ## Xiami
        - '*.xiami.com'
        ## Migu
        - '+.music.migu.cn'
        # === Game Service ===
        ## Nintendo Switch
        - '+.srv.nintendo.net'
        ## Sony PlayStation
        - '+.playstation.net'
        - '+.playstation.com'
        - '+.stun.playstation.net'
        ## Microsoft Xbox
        - 'xbox.*.microsoft.com'
        - '+.xboxlive.com'
        # === Other ===
        ## QQ Quick Login
        - 'localhost.ptlogin2.qq.com'
        ## Golang
        - 'proxy.golang.org'
        ## STUN Server
        - 'stun.*.*'
        - 'stun.*.*.*'
        ## Bilibili CDN
        - '*.mcdn.bilivideo.cn'
        # === Other ===
        - '*.bilibili.com'
        - '*.1huizhan.com'
        - '*.3.cn'
        - '*.300hu.com'
        - '*.360buy.cn'
        - '*.360buy.com'
        - '*.360buy.com.cn'
        - '*.360buyimg.com'
        - '*.360buyinternational.com'
        - '*.360top.com'
        - '*.jd.com'
    
    nameserver:
        - 114.114.114.114 # default value
        - 8.8.8.8
        - tls://223.5.5.5:853 # DNS over TLS
        - https://doh.pub/dns-query
        - https://dns.alidns.com/dns-query#h3=true 
        - 192.168.31.1
 # 锚点
#pg: &pg {type: select, proxies: [Proxy, Manual, OpenAI, Streaming, Auto-Urltest, FINAL, DIRECT]}
p: &p {type: http, interval: 86400, health-check: {enable: true, url:  http://www.gstatic.com/generate_204, interval: 1800}}
auto: &auto {type: url-test, lazy: true, url:  http://www.gstatic.com/generate_204, interval: 900, tolerance: 0, use: [Subscribe]}
select: &select {type: select, use: [Subscribe]}
c: &c {type: http, behavior: classical, interval: 86400}
d: &d {type: http, behavior: domain, interval: 86400}
i: &i {type: http, behavior: ipcidr, interval: 86400}

proxy-providers:
  Subscribe: {<<: *p, path: ./proxy-providers/Sub.yaml, url: https://rssteacat1.xyz/api/v1/client/subscribe?token=26de534f2c8cbf15f6e28e2467278aef}
       
               
proxies: null

proxy-groups:
  #分流分组
  - {name: Domestic, type: select, proxies: [DIRECT, Auto-Urltest, Manual]}
  
  - {name: Proxy, type: select, proxies: [Auto-Urltest, Manual, DIRECT]}
  
  - {name: Manual, <<: *select}
  
  - {name: OpenAI, type: select, proxies: [Manual, Auto-Urltest, DIRECT]}
  
  - {name: Streaming, type: select, proxies: [Auto-Urltest, Manual, DIRECT]}
  
  - {name: Auto-Urltest, <<: *auto}
  
  - {name: FINAL, type: select, proxies: [DIRECT, Manual, Auto-Urltest]}

rule-providers:  
  Lan: {<<: *c, format: text, path: ./rule-providers/Lan.list,  url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Lan/Lan.list}
  Download: {<<: *c, format: text, path: ./rule-providers/Download.list,  url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Download/Download.list}
  AD: {<<: *d, format: text, path: ./rule-providers/AD.list, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AdvertisingLite/AdvertisingLite.list}
  Apple: {<<: *c, format: text, path: ./rule-providers/Apple.list,  url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple.list}
  Github: {<<: *c, format: text, path: ./rule-providers/Github.list,  url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub.list}
  YouTube: {<<: *c, format: text, path: ./rule-providers/YouTube.list,  url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.list}
  Google: {<<: *c, format: text, path: ./rule-providers/Google.list,  url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.list}
  Telegram: {<<: *c, format: text, path: ./rule-providers/Telegram.list,  url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.list}
  Twitter: {<<: *c, format: text, path: ./rule-providers/Twitter.list,  url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Twitter/Twitter.list}
  Direct+: {<<: *c, format: text, path: ./rule-providers/Direct+.list,  url: https://cdn.jsdelivr.net/gh/tokuwakana/rules@main/Direct+.list}
  Steam: {<<: *c, format: text, path: ./rule-providers/steamcn.list,  url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/SteamCN/SteamCN.list}
  Battle: {<<: *c, format: text, path: ./rule-providers/Battle.list,  url:  https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Battle/Battle.list}
  AI: {<<: *c, format: text, path: ./rule-providers/AI.list,  url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.list}
  ChinaDomain: {<<: *c, format: text, path: ./rule-providers/ChinaDomain.list,  url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaDomain.list}
  Proxy+: {<<: *c, format: text, path: ./rule-providers/Proxy+.list,  url: https://cdn.jsdelivr.net/gh/tokuwakana/rules@main/Proxy+.list}
  ProxyMedia: {<<: *c, format: text, path: ./rule-providers/ProxyMedia.list,  url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia.list}
  ProxyGFW: {<<: *c, format: text, path: ./rule-providers/ProxyGFW.list,  url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ProxyLite/ProxyLite.list}
 # speedtest: {<<: *c, format: text, path: ./rule-providers/speedtest.list,  url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Speedtest/Speedtest.list}

rules:
  - RULE-SET,Github,Proxy
  - RULE-SET,Lan,DIRECT 
  - RULE-SET,Download,DIRECT
  - RULE-SET,Direct+,DIRECT
  - RULE-SET,AD,REJECT
  - RULE-SET,Proxy+,Proxy
  - RULE-SET,AI,OpenAI
  - RULE-SET,Battle,Proxy
  - RULE-SET,Apple,Domestic
  - RULE-SET,YouTube,Proxy
  - RULE-SET,Google,Proxy
  - RULE-SET,Telegram,Proxy
  - RULE-SET,Twitter,Proxy
  - RULE-SET,Steam,Domestic
  - RULE-SET,ProxyMedia,Streaming
  - RULE-SET,ProxyGFW,Proxy 
  - RULE-SET,ChinaDomain,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,FINAL

